---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: add-proxy
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./my-flux
  prune: false
  sourceRef:
    kind: GitRepository
    name: labs
