---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: labs
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: test/flux
  url: https://github.com/egarciam/tkng-labs.git
