apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - my-install.yaml
patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: all
      spec:
        template:
          spec:
            containers:
              - name: manager
                env:
                  - name: "https_proxy"
                    value: "http://10.113.55.34:8080"
                  - name: "http_proxy"
                    value: "http://10.113.55.34:8080"
                  - name: "no_proxy"
                    value: "localhost,127.0.0.1,10.0.0.0/8,.cluster.local.,.cluster.local,.svc,172.0.0.0/8,localhost"      
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/part-of=flux