---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cni
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./manifests/cilium
  prune: true
  sourceRef:
    kind: GitRepository
    name: labs

